### ISSUE TITLE
Fix Search Paginator to use x-total-count

### ISSUE THREAD

**Issue by rnikoopour** [sailpoint-oss/golang-sdk#17]
https://github.com/sailpoint-oss/golang-sdk/blob/cd65ccd99bff2fc1c7f788bbe27b59bf51acdb3c/paginator.go#L39-L42

This current implementation does not work when searching for access profiles.  Access Profiles return 50 results when setup with the default search configuration.  When passed into the paginator 50 < 250 resulting in this exiting without a complete search being run.

Paginator should use the `x-total-count` header instead of testing if the total current results are less than the expected increment.

**Comment by philip-ellis-sp** [comment]
The reason we do not use the x-total-count in the pagination is because there are performance implications when enabling. Some queries can take much longer by enabling the total count feature so it's normally best to not enable it unless there is a specific need. In the case of some non standard implementations like the above, you can simply use the non-default paginator and it should work properly with the correct parameters. Ideally, all our endpoints would follow the standard of 250 results.

**Comment by rnikoopour** [comment]
Will close this issue. Ty for sharing :D
